### ISSUE TITLE
Three versions in Godot AssetLib?

### ISSUE THREAD

**Issue by lethefrost** [yudinikita/godot-spin-button#2]
Hi there! Thank you for this cool component library. I just noticed that there are 3 of them in the Godot AssetLib and didn't find any difference in their description/version info, so I hope to report this to you. I am wondering if they are all copies of the same library, just mistakenly duplicated, or they are there serving different purposes?

**Comment by Calinou** [comment]
I've unlisted the 4.1 and 4.2 versions of the add-on, as you only need to keep the lowest version listed (which will be listed for all 4.x users that use the same version, or a newer minor version).

**Comment by yudinikita** [comment]
> I've unlisted the 4.1 and 4.2 versions of the add-on, as you only need to keep the lowest version listed (which will be listed for all 4.x users that use the same version, or a newer minor version).

Thank you! That's exactly what I needed.
